spring:
  profiles:
    include: jwt
    group:
      "dev-profile": "dev,jwt"
      "prod-profile": "prod,jwt"

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/jpa
    username: sa
    password:

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

    hibernate:
      ddl-auto: create

logging:
  level:
    org.apache.coyote.http11: debug

    com.example.myboard : info
